# Generated by Django 4.2.14 on 2024-07-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.TextField(default='To be written...'),
        ),
        migrations.AddField(
            model_name='item',
            name='time_to_cook',
            field=models.IntegerField(default='-1'),
        ),
    ]
